### ISSUE TITLE
ITC-3 runner problem

### ISSUE THREAD

**Issue by emiltin** [rsmp-nordic/rsmp_implementations#37]
github actions report:

The self-hosted runner: itc3 lost communication with the server. Verify the machine is running and has a healthy network connection. Anything in your workflow that terminates the runner process, starves it for CPU/Memory, or blocks its network access can cause this error.

**Comment by emiltin** [comment]
latest run has beeen queued for an hour now. looks like the PC or equipment is down

**Comment by otterdahl** [comment]
> latest run has beeen queued for an hour now. looks like the PC or equipment is down

I've contacted Swarco
