### ISSUE TITLE
EC-2 can't download log

### ISSUE THREAD

**Issue by emiltin** [rsmp-nordic/rsmp_implementations#38]
the EC-2 is online again, which is great.

but there's an issue with the workflow, in the step 'Get ec2 rsmp log':

Run Remove-Item Alias:curl
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0curl: (6) Could not resolve host: tmp
Error: Process completed with exit code 1.

**Comment by otterdahl** [comment]
Right. It's because we moved the workflows between repositories.
The environment variables needs be moved as well. I think I fixed it now.
