### ISSUE TITLE
Swarco ITC-2 uses incorrect "category"

### ISSUE THREAD

**Issue by otterdahl** [rsmp-nordic/rsmp_implementations#4]

**Comment by otterdahl** [comment]
It usually uses "cat":"b", but only "D" is used for traffic signals. See https://rsmp-nordic.github.io/rsmp_sxl_traffic_lights/sxl_traffic_light_controller.html#alarms

**Comment by otterdahl** [comment]
This happens in version 6.94.24.
This issue is fixed in ITC-3

**Comment by otterdahl** [comment]
Fixed in versions 6.96.0 at later

**Comment by emiltin** [comment]
can be closed then?

**Comment by otterdahl** [comment]
Yes. I think so
