### ISSUE TITLE
ITC-3: Custom error messages not mapped to RSMP Alarm

### ISSUE THREAD

**Issue by otterdahl** [rsmp-nordic/rsmp_implementations#47]
There is a possibility to create custom error messages in ITC-3. They show up as alarms in the controller, but are not sent using RSMP. They should map as A0009 (other error). A0009 used for [other errors not covered by any other alarm type.](https://rsmp-nordic.org/rsmp_specifications/rsmp_sxl_traffic_lights/1.1/sxl_traffic_light_controller.html#a0009)

**Comment by emiltin** [comment]
hi david, i suggest we use the validator repo for bug report also for equipment, and close this repo? what do you think, is there still a need for this repo? i think it's less confusing just to have one repo, then we can use labels to tag bugs in equipment.

**Comment by otterdahl** [comment]
Yes. It's certainly less confusing and we can make the change. I can recreate the latest issues in validator repo instead. We should be careful a migrate any older existing open issues to the validator also before closing this repo.

**Comment by emiltin** [comment]
issues can be moved between repos - should i move them?

**Comment by otterdahl** [comment]
Yes. feel free to do so
